In [1]:
###Load libraries
import awscli
import selenium
import boto3
import pandas as pd
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


###call the webdriver
browser = webdriver.Chrome("/Users/apurvwaghule/Desktop/IA Assignment/Week 8/chromedriver")

browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities_action.jsp?orgName=T&d-49653-p=2&city=&searchType=contains&reg1=&project=Charities&reg3=&reg2=&ein=&orgId=&num1=&state=none&regType=ALL&num2=')

#identify xpath of location to select element
inputElement = browser.find_element(By.XPATH,"/html/body/div[2]/div/table/tbody/tr/td[3]/div/div/table[2]/tbody")


#identify the table to scrape
table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')

print(table)

<ipython-input-1-017a8460476f>:12: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome("/Users/apurvwaghule/Desktop/IA Assignment/Week 8/chromedriver")

<selenium.webdriver.remote.webelement.WebElement (session="2120c20f038422a06982d7929c612319", element="8e40ec3c-ca7b-4712-b951-ecf6e39038b7")>

In [2]:
#create empty dataframe
df =[]

#loop through dataframe to export table
for row in table.find_elements(By.CSS_SELECTOR,'tr'):
      cols = df.append([cell.text for cell in row.find_elements(By.CSS_SELECTOR,'td')])


#update dataframe with header 
df = pd.DataFrame(df, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])
df.drop(index=df.index[0], axis=0, inplace=True) # to drop first row which is none
display(df) #let's have a look at the data before creating the CSV file and loading it into s3

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
0,None,None,None,None,None,None
1,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
2,1 CLUB COLOMBIA CARIBE INTERNATIONAL,15-79-51,NO DATA AVAILABLE,NFP,QUEENS,NY
3,1 in 9 The Long Island Breast Cancer Action Co...,05-26-54,113195645,NFP,BALDWIN,NY
4,Academy of General Dentistry Foundation,43-07-85,237310583,NFP,ALBANY,NY
5,ALS ASSOCIATION UPSTATE NEW YORK CHAPTER,21-23-76,412129176,NFP,ELBRIDGE,NY
6,"American Agora Foundation, Inc.",40-62-78,204000236,NFP,NEW YORK,NY
7,AMERICAN CLASSICAL ORCHESTRA INC,15-89-17,061072470,NFP,NEW YORK,NY
8,"AOPA Foundation, Inc.",40-51-26,208817225,NFP,FREDERICK,MD
9,ARNOLD GOLD FOUNDATION,21-38-43,223052098,NFP,ENGLEWOOD CLIFFS,NJ
10,"Balanda Community Association, Inc.",42-90-86,264154665,NFP,DENVER,CO
11,BLESSING WAY FOUNDATION,20-76-19,043138834,NFP,NEW YORK,NY
12,BOYS & GIRLS CLUB OF THE NORTHTOWNS FOUNDATION...,01-23-16,160844107,NFP,BUFFALO,NY
13,BRAND FOUNDATION OF NEW YORK INC,00-12-93,136159106,NFP,NEW YORK,NY
14,Briar Foundation,42-66-39,356829452,NFP,LARCHMONT,NY
15,BROOKLYN GYNECOLOGICAL SOCIETY INC,05-02-76,011202369,NFP,BROOKLYN,NY

In [19]:
#load file into s3. Pandas actually leverages boto to connect to s3 and can push the file directly into an s3 bucket
df.to_csv('charities_bureau_scrape_', header=True, line_terminator='\n')

In [22]:
# uploading to s3 
import boto3 
s3 = boto3.resource('s3')
s3.meta.client.upload_file('charities_bureau_scrape_.csv', 'apurvbt2', 'charities_bureau_scrape_800746903')

In [23]:
#print success message
#checking the files which are available in the s3 bucket we created 'apurvbt2'. 
# We uploaded charities csv file with name 'charities_bureau_scrape_800746903'

my_bucket = s3.Bucket('apurvbt2')

for my_bucket_object in my_bucket.objects.all():
    print(my_bucket_object.key)

Information_arch_{Waghule_Apurva}_Assignment_8a
charities_bureau_scrape_800746903